# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.0.0
maven_group = io.bluestaggo
archives_base_name = unused13restoration

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.3-pre-07261249
feather_build = 23
nests_build = 7
loader_version = 0.16.14
